variable "database_name" {
  description = "The name of the Ms SQL Database. Changing this forces a new resource to be created."
}

variable "tags" {
  description = "Tags to be passed to created instances"
  default     = {}
}

variable "resource_group_name" {
  description = "The name of the resource group where the SQL server resides"
}

variable "server_version" {
  description = "The version of the MSSQL server."
  default     = "12.0"
}

variable "max_size_gb" {
  description = "the max size of the database in gigabytes."
  default     = 20
}

variable "admin_login_name" {
  description = "The administrator login name for the SQL Server"
  default     = ""
}

variable "server_name" {
  description = "The name of the server to be created"
  default     = ""
}

variable "create_vnet_rule" {
  description = "whether to create the vnet rule. The subnet passed must have the Microsoft.Sql service endpoint enabled"
  default     = false
}

variable "vnet_rule_name" {
  description = "The name of the SQL virtual network rule to be created"
  default     = ""
}

variable "public_network_access_enabled" {
  description = "Whether or not public network access is allowed for this server"
  default     = false
}

variable "create_private_endpoint" {
  description = "Whether to create a private endpoint access for the SQL Server. The subnet id must be provided ifthis is true and must have enabled private_link_endpoints"
  default     = false
}

variable "private_endpoint_name" {
  description = "The name of the private endpoint to be created. If not provided it is autogenerated when create_private_endpoint is true"
  default     = ""
}

variable "subnet_id" {
  description = "The subnet id to attach private_endpoint/vnet firewall rule to"
  default     = ""
}
