variable "database_name" {
  description = "The name of the Ms SQL Database. Changing this forces a new resource to be created."
}

variable "tags" {
  description = "Tags to be passed to created instances"
  default     = {}
}

variable "resource_group_name" {
  description = "The name of the resource group where the SQL server resides"
}

variable "server_version" {
  description = "The version of the MSSQL server."
  default     = "12.0"
}

variable "max_size_gb" {
  description = "the max size of the database in gigabytes."
  default     = 20
}

variable "admin_login_name" {
  description = "The administrator login name for the SQL Server"
  default     = ""
}

variable "server_name" {
  description = "The name of the server to be created"
  default     = ""
}

variable "create_vnet_rule" {
  description = "whether to create the vnet rule"
  default     = false
}

variable "vnet_rule_name" {
  description = "The name of the SQL virtual network rule to be created"
  default     = ""
}

variable "public_network_access_enabled" {
  description = "Whether or not public network access is allowed for this server"
  default     = false
}

variable "create_private_endpoint" {
  description = "Whether to create a private endpoint access for the SQL Server. The subnet id must be provided ifthis is true"
  default     = false
}

variable "private_endpoint_name" {
  description = "The name of the private endpoint to be created. If not provided it is autogenerated when create_private_endpoint is true"
  default     = ""
}

variable "subnet_id" {
  description = "The subnet id to attach private_endpoint/vnet firewall rule to. For Vnet firewall rule, The subnet passed must have the Microsoft.Sql service endpoint enabled"
  default     = ""
}

variable "private_dns_zone_name" {
  description = "The Private DNS Zone to use to create the Private FQDN for the SQL server if private. Once specified, an FQDN is created for the Private Link"
  default     = null
}

variable "private_fqdn_subdomain" {
  description = "The subdomain to deploy database on for the private_dns_zone"
  default     = ".database"
  type        = string
}

variable "allow_access_to_azure_services" {
  description = "Makes server accessible to Authenticated requests from Azure services"
  default     = false
}

variable "clients_ip" {
  description = "A list of client IPs to be whitelisted for access to SQL Server. Example [{start_ip: 0.0.0.0, end_ip: 0.0.0.1},]"
  type        = list(map(string))
  default     = []
}
